<!--Cette page permet de connecter l'administrateur-->

<?php if (session_status() === PHP_SESSION_NONE) session_start(); ?>
<?php include_once $_SESSION['ROOT_PATH'] . 'application/php/flash_message.php' ?>

<?php if (isset($_SESSION['connected']) && $_SESSION['connected']): ?>
    <form method="POST" action="application/php/controllers/loginAdminController.php" class="form">
        <button type="submit" name="deconnection">Confirmer la déconnection</button>
    </form>
<?php else: ?>
    <h3>Connexion Administrateur</h3>
    <form method="POST" action="application/php/controllers/loginAdminController.php" class="form">
        <input type="text" placeholder="Nom d'utilisateur" name="admin_name">
        <input type="password" placeholder="Mot de passe" name="admin_password">
        <div class="g-recaptcha" data-sitekey="6LetI7MUAAAAAGGP6jQFl30oOqLp1-Rfqz1vPq-J"></div>
        <p>
            <button type="submit" name="connection">Connection</button>
        </p>
    </form>
<?php endif; ?>

