<!--Cette page permet d'ajouter une recette-->
<?php require_once $_SESSION['ROOT_PATH'] . 'application/php/flash_message.php'; ?>
<?php require_once $_SESSION['ROOT_PATH'] . 'application/php/is_admin.php' ?>

<?php if (array_key_exists('error', $_GET) && !empty($_GET['error'])): ?>
    <p class="error">
        <?= htmlspecialchars($_GET['error']) ?>
        <?= $_SESSION['name'] ?>
    </p>
<?php endif; ?>
<h2>Ajouter une recette</h2>
<form action="application/php/controllers/addRecipeController.php" method="POST" class="form"
      enctype="multipart/form-data">
    <label for="name">Nom</label>
    <input type="text" id="name" name="name" placeholder="Nom de la recette" required>

    <label for="photo">Choisir une photo</label>
    <figure>
        <!-- Grâce à la fonction readURL, on ne génère le src et le alt de l'image que s'il y en a une déjà choisie.
        Ainsi on peut la faire appaître à ce moment. Le src d'origine est pour générer une image vide de 26 octets-->
            <img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" class="photo image_recette" alt="Photo de la recette">
    </figure>
    <input type="file" id="photo" name="photo" accept="image/*" onchange="readURL(this);"/>

    <label for="ingredients_list">Ingrédients</label>
    <textarea id="ingredients_list" name="ingredients_list" placeholder="Liste des ingrédients" rows="10"
              required></textarea>

    <label for="how_many_persons">Personnes</label>
    <input type="text" id="how_many_persons" name="how_many_persons" placeholder="Combien de personnes" required>

    <label for="cooking_time_minutes">Temps de cuisson</label>
    <input type="text" id="cooking_time_minutes" name="cooking_time_minutes" placeholder="Temps en minutes" required>

    <label for="cooking_instructions">Intructions</label>
    <textarea id="cooking_instructions" name="cooking_instructions" placeholder="Instructions" rows="10"
              required></textarea>

    <label for="category">Catégorie</label>
    <select name="category" id="category" required>
        <option value="" disabled selected>Type de plat</option>
        <option value="Entrée">Entrée</option>
        <option value="Plat">Plat</option>
        <option value="Dessert">Dessert</option>
    </select>

    <label for="note">Notes</label>
    <textarea id="note" name="note" placeholder="Notes / Instructions supplémentaires" rows="5"></textarea>

    <button type="submit" name="submit">Enregistrer</button>
</form>