<!--Recette incluse dans la recette cliquée après la recherche, ou la page des recettes-->


<article id="view-recipe-article">
    <h3><?= htmlspecialchars($recette_from_id['name']) ?></h3>
    <div>
        <figure>
            <img src="img/<?= htmlspecialchars($recette_from_id['photo']) ?>"
                 alt="<?= htmlspecialchars($recette_from_id['name']) ?>" class="view-recipe-image">
        </figure>
        <section>
            <h5>Catégorie&nbsp;:&nbsp;<span><?= htmlspecialchars($recette_from_id['category']) ?></span></h5>
            <h5>Pour <span><?= htmlspecialchars($recette_from_id['how_many_persons']) ?></span> personnes</h5>
            <h5>Temps de cuisson : <span><?= htmlspecialchars($recette_from_id['cooking_time_minutes']) ?> mn</span>
            </h5>
        </section>
    </div>
    <h4>Ingrédients :</h4>
    <p><?= nl2br(htmlspecialchars($recette_from_id['ingredients_list'])) ?></p>
    <h4>Instructions :</h4>
    <p><?= nl2br(htmlspecialchars($recette_from_id['cooking_instructions'])) ?></p>
    <?php if (!empty($recette_from_id['note'])): ?>
        <h4>Notes&nbsp;:</h4>
        <p><?= nl2br(htmlspecialchars($recette_from_id['note'])) ?></p>
    <?php endif; ?>
    <p><?= nl2br(htmlspecialchars($recette_from_id['note'])) ?></p>
    <h4>Date de création :</h4>
    <p id="recipe"><?= htmlspecialchars($recette_from_id['creation_date_formatted']) ?></p>
    <br>
</article>
