<header>
    <h1>Recettes Omnicuiseur</h1>
    <nav id="mainNavigation">
        <ul>
            <li><a href="index.php?page=home">Accueil</a></li>
            <li><a href="index.php?page=recipes">Voir</a></li>
            <li><a href="index.php?page=login_admin">Admin</a></li>
            <li><a href="index.php?page=add_recipe">Ajouter</a></li>
            <li><a href="index.php?page=edit_recipes">Editer</a></li>
        </ul>
    </nav>
    <p>Recettes disponibles : <span><?= $recipeQuantity ?></span></p>
</header>