<!--Page d'accueil-->
<aside>
    <?php include_once'application/php/flash-message.php'; ?>
    <h2>Dernière recette</h2>
    <a href="index.php?page=recipes&action=first">
        <h3><?= htmlspecialchars($last_recipe['name']) ?></h3>
        <figure>
            <img src="img/<?= htmlspecialchars($last_recipe['photo']) ?>"
                 alt="<?= htmlspecialchars($last_recipe['name']) ?>">
        </figure>
    </a>
</aside>