<!--page d'accueil-->
<aside>
<?php include('application/php/flash_message.php'); ?>
    <h2>Dernière recette créée</h2>
    <h3><?= htmlspecialchars($recettes['name']) ?></h3>
    <a href="index.php?page=recipes&action=first">
        <img src="img/<?= htmlspecialchars($recettes['photo']) ?>" alt="<?= htmlspecialchars($recettes['name']) ?>"
             title="<?= htmlspecialchars($recettes['name']) ?>">
    </a>
</aside>