<?php ob_start(); ?>
    <!doctype html>
    <html lang="fr">
    <head>
        <title>Recettes pour l'Omnicuiseur</title>
        <meta name="Description"
              content="Recettes pour l'omnicuiseur vitalité. Fait partie du Portfolio de Jean Liautaud">
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!--    Favicon-->
        <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png">

        <!-- CSS -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
              integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz"
              crossorigin="anonymous">

        <link href='//fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="css/normalize.css">
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <link rel="stylesheet" type="text/css" href="css/base.css">
        <!-- Chargement de la librairie jquery -->
        <!--    <script src="/js/jquery-3.4.1.min.js"></script>-->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    </head>
    <body>
    
    <?php include 'header.phtml' ?>

    <!-- Google reCAPTCHA-->
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <noscript>
        <p>Javascript n'est pas activé !</p>
        <p>Javascript is not enabled!</p>
    </noscript>
    <main class="container center">
        <h1>En Construction</h1>
        <!-- Chargement du template PHTML spécifié par dispatcher.php -->
        <?php include "application/view/$template.phtml"; ?>
    </main>
    <script src="js/main.js"></script>
    </body>
    </html>
<?php ob_get_flush(); ?>