<?php include_once 'application/php/flash_message.php' ?>
<?php     unset($_SESSION['connected']); ?>

<form method="POST" action="application\php\login_admin.php" class="form">
    <input type="text" placeholder="Nom d'utilisateur" name="admin_name">
    <input type="password" placeholder="Mot de passe" name="admin_password">
    <button type="submit" name="connection">Connection</button>
</form>