<!--page afficher une recette parmi d'autres-->

<p>Recette N°  <?= $_SESSION['indexCurrentRecipe'] + 1 ?> / <?= $recipeQuantity ?></p>
<nav id="recipe_navigation">
    <a href="<?php echo 'index.php?page=recipes&action=first'?>" title="Début"><i class="fas fa-fast-backward"></i></a>
    <a href="<?php echo 'index.php?page=recipes&action=previous'?>" title=Précédente"><i class="fas fa-step-backward"></i></a>
    <a href="<?php echo 'index.php?page=recipes&action=next'?>" title="Suivante"><i class="fas fa-step-forward"></i></a>
    <a href="<?php echo 'index.php?page=recipes&action=last'?>" title="Dernière"><i class="fas fa-fast-forward"></i></a>
</nav>
<article id="view_recipe_article">
    <h3><?= htmlspecialchars($recette_from_id['name']) ?></h3>
    <img src="img/<?= htmlspecialchars($recette_from_id['photo']) ?>"
         alt="<?= htmlspecialchars($recette_from_id['name']) ?>"
         title="<?= htmlspecialchars($recette_from_id['name']) ?>" class="viewRecipeImage">

    <h4>Catégorie :</h4><p><?= htmlspecialchars($recette_from_id['category'])?></p>
    <h4>Pour <?= htmlspecialchars($recette_from_id['how_many_persons'])?> personnes</h4>
    <h4>Temps de cuisson :</h4><p><?= htmlspecialchars($recette_from_id['cooking_time_minutes'])?> mn</p>
    <h4>Ingrédients :</h4><p><?= nl2br(htmlspecialchars($recette_from_id['ingredients_list']))?></p>
    <h4>Instructions :</h4>
<!--    TODO Verfifier de partout nl2br-->
    <p><?= nl2br(htmlspecialchars($recette_from_id['cooking_instructions']))?></p>
    <h4>Notes :</h4>
    <p><?= nl2br(htmlspecialchars($recette_from_id['note'])) ?></p>
    <h4>Date de creation :</h4><p id="recipe"><?= htmlspecialchars($recette_from_id['creation_date_formatted'])?></p>
</article>
