<!--page qui permet d'afficher une recette parmi d'autres et de naviguer parmi elles-->

<p>Recette N° <?= $_SESSION['indexCurrentRecipe'] + 1 ?> / <?= $recipes_quantity ?></p>
<nav id="recipe-navigation">
    <a href="<?= 'index.php?page=recipes&action=first' ?>" title="Première"><i class="fas fa-fast-backward"></i></a>
    <a href="<?= 'index.php?page=recipes&action=previous' ?>" title="Précédente"><i
                class="fas fa-step-backward"></i></a>
    <a href="<?= 'index.php?page=recipes&action=next' ?>" title="Suivante"><i
                class="fas fa-step-forward"></i></a>
    <a href="<?= 'index.php?page=recipes&action=last' ?>" title="Dernière"><i
                class="fas fa-fast-forward"></i></a>
</nav>

<?php include_once 'article-recipe.phtml' ?>