<!--Cette page affiche un formulaire de recherche, ainsi que le résultat de la recherche précédente-->
<?php if (session_status() === PHP_SESSION_NONE) session_start(); ?>
<!--<div id="home"></div>-->
<form method="POST" action="application/php/controllers/searchController.php" class="form" id="home">
    <label for="search_item">Recherche (dans titre ou description) <br><span class="italic">Ex : chocolat</span>
    </label>
    <input type="text" id="search_item" name="search_item" placeholder="Que recherchez vous ?" required>
    <p>
        <button type="submit" name="submit">Rechercher</button>
    </p>
</form>

<?php if (isset($_SESSION['search_result_list_recipes'])): ?>
    <?php $list_recipes = $_SESSION['search_result_list_recipes'] ?>
    <table class="recettes search-result center">
        <caption><?= count($list_recipes) ?> Résultats pour
            "<?php if (isset($_SESSION['search_item'])): ?>
                <?= htmlspecialchars($_SESSION['search_item']) ?>
            <?php endif; ?>"
        </caption>
        <thead>
        <tr>
            <th>Photo</th>
            <th>Nom</th>
            <th>Date</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($list_recipes as $list_recipe): ?>
            <tr onclick="document.location='index.php?page=recipe-from-search&id=<?= $list_recipe['id'] ?>'">
                <td>
                    <figure><img src="img/<?= htmlspecialchars($list_recipe['photo']) ?>"
                                 alt="" width="100px" height="auto" class="photo"></figure>
                </td>
                <td class="td nom"><?= htmlspecialchars($list_recipe['name']) ?></td>
                <td class="td date"><?= htmlspecialchars($list_recipe['creation_date_formatted']) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <a href="#home">
        <button type="button" class="button-scroll-to-top"><i class="fas fa-arrow-up"></i></button>
    </a>
<?php endif; ?>
